### ISSUE TITLE
Plugin fails to load on Cura 5.1.0 (Windows 10)

### ISSUE THREAD

**Issue by cel22262** [FlyingSamson/SpaceMouseTool#10]
Exception: Import error loading module SpaceMouseTool
2022-07-20 08:40:54,183 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [732]: Traceback (most recent call last):
2022-07-20 08:40:54,184 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [732]:   File "UM\PluginRegistry.py", line 730, in _findPlugin
2022-07-20 08:40:54,184 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [732]:     module = imp.load_module(plugin_id, file, path, desc)  # type: ignore #MyPy gets the wrong output type from imp.find_module for some reason.
2022-07-20 08:40:54,185 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [732]:   File "imp.py", line 245, in load_module
2022-07-20 08:40:54,186 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [732]:   File "imp.py", line 217, in load_package
2022-07-20 08:40:54,186 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [732]:   File "<frozen importlib._bootstrap>", line 719, in _load
2022-07-20 08:40:54,187 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [732]:   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
2022-07-20 08:40:54,187 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [732]:   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2022-07-20 08:40:54,188 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [732]:   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2022-07-20 08:40:54,188 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [732]:   File "C:\Users\Rift\AppData\Roaming\cura\5.1\plugins\SpaceMouseTool\__init__.py", line 4, in <module>
2022-07-20 08:40:54,189 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [732]:     from . import SpaceMouseTool
2022-07-20 08:40:54,190 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [732]:   File "C:\Users\Rift\AppData\Roaming\cura\5.1\plugins\SpaceMouseTool\SpaceMouseTool.py", line 29, in <module>
2022-07-20 08:40:54,190 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [732]:     from .lib.pyspacemouse import set_logger, start_spacemouse_daemon, release_spacemouse_daemon
2022-07-20 08:40:54,191 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [732]: ImportError: DLL load failed while importing pyspacemouse: The specified module could not be found.
2022-07-20 08:40:54,191 - WARNING - [MainThread] UM.PluginRegistry._populateMetaData [824]: Could not find plugin SpaceMouseTool

ALSO main module import needs to be updates from PyQt5 to PyQt6

**Comment by FlyingSamson** [comment]
Can you try the recent version on `master`? This should at least fix the issue with PyQt6 and maybe the other one, too?!

Sorry, I did not yet create a new release. Maybe I will find the time next weekend.

**Comment by FlyingSamson** [comment]
I finally found the time to bundle the current version in a release (v1.3.0). Please give this a try.

**Comment by FlyingSamson** [comment]
Closing this for now. If the problem persists, feel free to reopen.

**Comment by FlyingSamson** [comment]
Closing this for now. If the problem persists, feel free to reopen.
